name: M


on:
  push


env:
  SERVER_HOST: '85.28.47.165'
  SERVER_USER: root
  SERVER_PATH: /var/www/trur/


jobs:


  deployJobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.PKEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
     
      # Deploy
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}
